### ISSUE TITLE
ModuleNotFoundError/ImproperlyConfigured /ImportError

### ISSUE THREAD

**Issue by doublyU** [csev/dj4e-samples#48]
### When tried to import models module to views.py, this way I got_ the error of  ImproperlyConfigured.

**from django.shortcuts import render
from models import Car

# Create your views here.
from django.http import HttpResponse

def index(request):
    return HttpResponse('Hello, word. You are at the polls index.')**

This Is the error here below 👇
(django3) C:\Users\Salam Taofeek\Desktop\django3\django_projects\mysite\polls>python views.py
Traceback (most recent call last):
  File "C:\Users\Salam Taofeek\Desktop\django3\django_projects\mysite\polls\views.py", line 2, in <module>
    from models import Car
  File "C:\Users\Salam Taofeek\Desktop\django3\django_projects\mysite\polls\models.py", line 4, in <module>
    class Car(models.Model):
  File "C:\Users\Salam Taofeek\Desktop\django3\lib\site-packages\django\db\models\base.py", line 127, in __new__
    app_config = apps.get_containing_app_config(module)
  File "C:\Users\Salam Taofeek\Desktop\django3\lib\site-packages\django\apps\registry.py", line 260, in get_containing_app_config
    self.check_apps_ready()
  File "C:\Users\Salam Taofeek\Desktop\django3\lib\site-packages\django\apps\registry.py", line 137, in check_apps_ready
    settings.INSTALLED_APPS
  File "C:\Users\Salam Taofeek\Desktop\django3\lib\site-packages\django\conf\__init__.py", line 87, in __getattr__
    self._setup(name)
  File "C:\Users\Salam Taofeek\Desktop\django3\lib\site-packages\django\conf\__init__.py", line 67, in _setup
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Requested setting INSTALLED_APPS, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.

### I tried another way to import it again this way 👇

**from django.shortcuts import render
from .models import Car

# Create your views here.
from django.http import HttpResponse

def index(request):
    return HttpResponse('Hello, word. You are at the polls index.')**

This is the error that I got here ( ImportError: attempted relative import with no known parent package)👇

(django3) C:\Users\Salam Taofeek\Desktop\django3\django_projects\mysite\polls>python views.py
Traceback (most recent call last):
  File "C:\Users\Salam Taofeek\Desktop\django3\django_projects\mysite\polls\views.py", line 2, in <module>
    from .models import Car
ImportError: attempted relative import with no known parent package

### Lastly I tired to import it this way too 👇

**from django.shortcuts import render
from gview.models import Car

# Create your views here.
from django.http import HttpResponse

def index(request):
    return HttpResponse('Hello, word. You are at the polls index.')**

Here is the error that I got (moduleNotFoundError) 👇

(django3) C:\Users\Salam Taofeek\Desktop\django3\django_projects\mysite\polls>python views.py
Traceback (most recent call last):
  File "C:\Users\Salam Taofeek\Desktop\django3\django_projects\mysite\polls\views.py", line 2, in <module>
    from gview.models import Car
ModuleNotFoundError: No module named 'gview'**m .models import Car
ImportError: attempted relative import with no known parent package

### Lastly I tired to import it this way too 👇

**from django.shortcuts import render
from gview.models import Car

# Create your views here.
from django.http import HttpResponse

def index(request):
    return HttpResponse('Hello, word. You are at the polls index.')**

Here is the error that I got (moduleNotFoundError) 👇

(django3) C:\Users\Salam Taofeek\Desktop\django3\django_projects\mysite\polls>python views.py
Traceback (most recent call last):
  File "C:\Users\Salam Taofeek\Desktop\django3\django_projects\mysite\polls\views.py", line 2, in <module>
    from gview.models import Car
ModuleNotFoundError: No module named 'gview'

**Comment by csev** [comment]
We do not provide student help here in github
